import base64
import os

# Create images directory if it doesn't exist
os.makedirs("assets/images", exist_ok=True)

# Logo - A simple "¡Español!" text with a flag-like background
logo_data = """
iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABmJLR0QA/wD/AP+gvaeTAAAA20lEQVR4nO3ZQQ6AIAwEQPD/X8YT
8WqIFdid+wKhXSgFAAAAAAAAAAAAgO/ZxxhzjJH9HMvYxvv+9muf2Q9AXUKCSEgQCQkiIUEkJIiEBJGQIBISREKCSEgQCQkiIUEkJIiE
BJGQIBISREKCSEgQCQkiIUEkJIiEBJGQIBISREKCSEgQCQkiIUEkJIiEBJGQIBISREKCSEgQCQkiIUEkJIiEBJGQIBISREKCSEgQCQki
IUEkJIiEBJGQIBISREKCSEgQCQkiIUEkJIiEBJGQIBISREKCSEgQCQkiIUEkJIiEBJGQIP8BfwEAAP//XsYGQqwE+g8AAAAASUVORK5CYII=
"""

# Owl mascot - A simple pixel art owl
owl_data = """
iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABmJLR0QA/wD/AP+gvaeTAAAA10lEQVR4nO3ZsQ3CQBAEQD6RAkiB
FEAKpABSACmQAkmBFEgBpEAKIAVSACmQAkiBFEAKpABSIAWSAimQFEiBpEAKJAVSICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVSICmQ
AkmBFEgKpEBSIAWSAimQFEiBpEAKJAVSICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVSICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVS
ICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVSICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVSICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVS
ICmQAkmBFEgKpEBSIAWSAimQFEiBpEAKJAVSICmQAkmBFEgKpEBSIAWSAimQFP8BfwEAAP//XsYGQqwE+g8AAAAASUVORK5CYII=
"""

# Save the images
with open("assets/images/logo.png", "wb") as f:
    f.write(base64.b64decode(logo_data))

with open("assets/images/owl.png", "wb") as f:
    f.write(base64.b64decode(owl_data)) 